
drop database QL_HETHONGGIAONHANH
go

CREATE DATABASE QL_HETHONGGIAONHANH
GO
USE QL_HETHONGGIAONHANH
GO


CREATE TABLE TAIKHOAN (
   ID char(5) not null,
   USERNAME varchar(20) not null,
   PASS varchar(20) not null,
   LOAITK int null,
   PRIMARY KEY (ID)
)

CREATE TABLE DOITAC 
(
	MADT varchar(10) NOT NULL,
	TAIKHOAN char(5) NOT NULL,
	MASOTHUE varchar(10) NOT NULL UNIQUE,
	EMAIL varchar(50),
	TENQUAN nvarchar(50),
	NGUOIDAIDIEN nvarchar(50),
	THANHPHO nvarchar(50),
	QUAN nvarchar(50),
	LOAIAMTHUC nvarchar(50),
	DIACHIKINHDOANH nvarchar(50),
	DIENTHOAI char(10),
	SOLUONGCUAHANG char(10),
	SOLUONGDHDUKIEN char(10)
	PRIMARY KEY (MADT)
)
CREATE TABLE TUYCHONMON
(
	TENMON nvarchar(80) NOT NULL,
	TUYCHON nvarchar(50) NOT NULL
	PRIMARY KEY (TENMON, TUYCHON)
)
CREATE TABLE MONAN
(
	TENMON nvarchar(80) NOT NULL,
	MIEUTAMON nvarchar(50),
	GIA float,
	TINHTRANGMONAN nvarchar(50)
	PRIMARY KEY (TENMON)
)
CREATE TABLE THUCDON
(
	MACUAHANG varchar(10) NOT NULL,
	MADT varchar(10) NOT NULL,
	TENMON nvarchar(80) NOT NULL,
	SOLUONGTON int,
	PRIMARY KEY (MACUAHANG,MADT,TENMON)
)
CREATE TABLE CUAHANG
(
	MACUAHANG varchar(10) NOT NULL,
	MADT varchar(10),
	TENCUAHANG nvarchar(50),
	DIACHI nvarchar(50),
	THOIGIANHOATDONG datetime,
	TINHTRANGCUAHANG nvarchar(50),

	ID_KHUVUC char(10)

	PRIMARY KEY (MACUAHANG,MADT)
)
CREATE TABLE HOPDONG
(
	MASOHOPDONG varchar(10) NOT NULL,
	NGAYLAP datetime,
	THOIGIANHIEULUC datetime,
	TAIKHOANNGANHANG varchar(20),
	PHIHOAHONG float,
	MADT varchar(10),
	MASOTHUE varchar(10),
	MANV varchar(10),
	TINHTRANGDUYET int
	PRIMARY KEY (MASOHOPDONG)
)
create table KHACHHANG
(
    MAKHACH varchar(10) NOT NULL,
	TAIKHOAN char(5) NOT NULL,
    TENKHACH nvarchar(30),
    DIENTHOAI char(10),
    DIACHI nvarchar(300),
    EMAIL varchar(30),
    PRIMARY KEY (MAKHACH)
)

create table DONHANG
(
    MADON varchar(10) NOT NULL,
    NGAYLAP datetime,
    HINHTHUCTT nvarchar(50),
    DIACHIGIAO nvarchar(300),
    PHISP float,
    PHIVC float,
    TONGTIEN float,
	TINHTRANG nvarchar(50) NOT NULL,
	NGAYGIAO datetime,
    MAKHACH varchar(10),
    TAIXE varchar(12),

	ID_KHUVUC char(10)

    PRIMARY KEY (MADON)
)

--create table CT_DONHANG(
--    MADON varchar(10) NOT NULL,
--    TENMON nvarchar(80) NOT NULL,
--	SOLUONG INT,
--	THANHTIEN float,
--    PRIMARY KEY (MADON,TENMON)
--)

--DROP TABLE CT_DONHANG
create table CT_DONHANG(
    MADON varchar(10) NOT NULL,
	MACUAHANG varchar(10),
	MADT varchar(10),
    TENMON nvarchar(80) NOT NULL,
	SOLUONG INT,
	THANHTIEN float,
    PRIMARY KEY (MADON,MACUAHANG,MADT,TENMON)
)
create table KHUVUC (
	ID_KHUVUC char(10) not null,
	TENKHUVUC nvarchar(50)

	constraint PK_KHUVUC primary key(ID_KHUVUC)
)

--update chỗ này mới
ALTER TABLE CT_DONHANG
ADD CONSTRAINT FK_CT_DONHANG_CUAHANG
FOREIGN KEY (MACUAHANG,MADT)
REFERENCES CUAHANG(MACUAHANG,MADT)

ALTER TABLE CT_DONHANG
ADD CONSTRAINT FK_CT_DONHANG_DONHANG
FOREIGN KEY (MADON)
REFERENCES DONHANG(MADON)

ALTER TABLE CT_DONHANG
ADD CONSTRAINT FK_CT_DONHANG_MONAN
FOREIGN KEY (TENMON)
REFERENCES MONAN(TENMON) ON DELETE CASCADE

ALTER TABLE CUAHANG
ADD CONSTRAINT FK_CUAHANG_KHUVUC FOREIGN KEY(ID_KHUVUC)
REFERENCES KHUVUC(ID_KHUVUC)

ALTER TABLE DONHANG
ADD CONSTRAINT FK_DONHANG_KHUVUC FOREIGN KEY(ID_KHUVUC)
REFERENCES KHUVUC(ID_KHUVUC)


CREATE TABLE NHANVIEN
(
    CMND varchar(10) NOT NULL,
	TAIKHOAN char(5) NOT NULL,
    HOTEN nvarchar(30),
    DIENTHOAI char(10),
    DIACHI nvarchar(30),
    EMAIL varchar(20),
    PRIMARY KEY (CMND)
)
CREATE TABLE TAIXE
(
    CMND varchar(12) NOT NULL,
	TAIKHOAN char(5) NOT NULL,
    HOTEN nvarchar(30),
    DIENTHOAI char(10),
    DIACHI nvarchar(30),
    EMAIL varchar(20),
    BIENSOXE varchar(5),
    TAIKHOANNGANHANG char(15),
    PHITHECHAN float,
	ID_KHUVUC char(10) NOT NULL
    PRIMARY KEY (CMND)
)
CREATE TABLE PHANHOI
(
	TENMON nvarchar(80) NOT NULL,
	MAKHACH varchar(10) NOT NULL,
	DANHGIA CHAR(7), -- LIKE OR DISLIKE
	BINHLUAN NVARCHAR(100)
	PRIMARY KEY(TENMON,MAKHACH)
)

ALTER TABLE KHACHHANG
ADD CONSTRAINT FK_KHACHHANG_TAIKHOAN 
FOREIGN KEY (TAIKHOAN)
REFERENCES TAIKHOAN (ID)

ALTER TABLE DOITAC
ADD CONSTRAINT FK_DOITAC_TAIKHOAN 
FOREIGN KEY (TAIKHOAN)
REFERENCES TAIKHOAN (ID)

ALTER TABLE NHANVIEN
ADD CONSTRAINT FK_NHANVIEN_TAIKHOAN 
FOREIGN KEY (TAIKHOAN)
REFERENCES TAIKHOAN (ID)

ALTER TABLE TAIXE
ADD CONSTRAINT FK_TAIXE_TAIKHOAN 
FOREIGN KEY (TAIKHOAN)
REFERENCES TAIKHOAN (ID)

ALTER TABLE DONHANG ADD CHECK (TINHTRANG IN (N'Đã hủy',N'Chờ xác nhận',N'Đã xác nhận',N'Đang chuẩn bị', N'Đang giao', N'Đã giao'))

ALTER TABLE DONHANG
ADD CONSTRAINT FK_DONHANG_KHACHHANG
FOREIGN KEY (MAKHACH)
REFERENCES KHACHHANG(MAKHACH)

ALTER TABLE DONHANG
ADD CONSTRAINT FK_DONHANG_TAIXE
FOREIGN KEY (TAIXE)
REFERENCES TAIXE(CMND)


ALTER TABLE CUAHANG
ADD CONSTRAINT FK_CUAHANG_DOITAC
FOREIGN KEY (MADT)
REFERENCES DOITAC(MADT)

ALTER TABLE HOPDONG
ADD CONSTRAINT FK_HOPDONG_DOITAC
FOREIGN KEY (MADT)
REFERENCES DOITAC(MADT)

ALTER TABLE THUCDON
ADD CONSTRAINT FK_THUCDON_CUAHANG
FOREIGN KEY (MACUAHANG,MADT)
REFERENCES CUAHANG(MACUAHANG,MADT)

ALTER TABLE THUCDON
ADD CONSTRAINT FK_THUCDON_MONAN
FOREIGN KEY (TENMON)
REFERENCES MONAN(TENMON) ON DELETE CASCADE

ALTER TABLE TUYCHONMON
ADD CONSTRAINT FK_TUYCHONMON_MONAN
FOREIGN KEY (TENMON)
REFERENCES MONAN(TENMON)

ALTER TABLE HOPDONG
ADD CONSTRAINT FK_HOPDONG_NHANVIEN
FOREIGN KEY (MANV)
REFERENCES NHANVIEN(CMND) ON DELETE CASCADE

ALTER TABLE PHANHOI 
ADD CONSTRAINT FK_MONAN_PHANHOI 
FOREIGN KEY (TENMON) 
REFERENCES MONAN(TENMON)

ALTER TABLE PHANHOI 
ADD CONSTRAINT FK_KHACHHANG_PHANHOI 
FOREIGN KEY (MAKHACH) 
REFERENCES KHACHHANG(MAKHACH)

ALTER TABLE PHANHOI ADD CHECK (DANHGIA = 'LIKE' OR DANHGIA = 'DISLIKE')

