EXEC sp_addlogin 'TK_VODANH', 'TK_VODANH123', 'QL_HETHONGGIAONHANH';  
CREATE USER VODANH FOR LOGIN TK_VODANH

GRANT SELECT, INSERT ON dbo.TAIKHOAN TO VODANH 
GRANT EXECUTE ON OBJECT::USP_LOGIN TO VODANH
--GRANT EXECUTE ON OBJECT::Sp_TaoTK_KH TO VODANH
GRANT SELECT, INSERT ON KHACHHANG TO VODANH


EXEC sp_addlogin 'TK_KHACHHANG', 'TK_KHACHHANG12345', 'QL_HETHONGGIAONHANH';  

CREATE USER KHACHHANG FOR LOGIN TK_KHACHHANG
GRANT EXECUTE ON OBJECT::USP_KH_TIMMONAN TO KHACHHANG

grant update, select
on KHACHHANG
to KHACHHANG

grant select
on DOITAC
to KHACHHANG

grant select
on CUAHANG
to KHACHHANG

grant select
on MONAN
to KHACHHANG

grant select
on THUCDON 
to KHACHHANG

grant select
on TUYCHONMON
to KHACHHANG

grant select
on DONHANG
to KHACHHANG

grant update
on DONHANG(TINHTRANG)
to KHACHHANG

grant select
on CT_DONHANG
to KHACHHANG
