USE QL_HETHONGGIAONHANH

EXEC sp_addlogin 'TK_VODANH', 'TK_VODANH123', 'QL_HETHONGGIAONHANH';  
CREATE USER VODANH FOR LOGIN TK_VODANH

GRANT SELECT, INSERT ON TAIKHOAN TO VODANH
GRANT SELECT, INSERT ON KHACHHANG TO VODANH
GRANT SELECT, INSERT ON TAIXE TO VODANH

GRANT EXECUTE ON OBJECT::USP_LOGIN TO VODANH
GRANT EXECUTE ON OBJECT::USP_CHECKUSERNAME TO VODANH
GRANT EXECUTE ON OBJECT::USP_CHECKPASS TO VODANH
GRANT EXECUTE ON OBJECT::USP_TAOTK_KHACHHANG TO VODANH
GRANT EXECUTE ON OBJECT::UPS_TX_TAOTK TO VODANH


--drop login TK_KHACHHANG
EXEC sp_addlogin 'TK_KHACHHANG', 'TK_KHACHHANG12345', 'QL_HETHONGGIAONHANH';  
CREATE USER KHACHHANG FOR LOGIN TK_KHACHHANG

GRANT SELECT, UPDATE ON KHACHHANG TO KHACHHANG
GRANT SELECT, INSERT ON DONHANG TO KHACHHANG
GRANT SELECT ON CUAHANG TO KHACHHANG
GRANT SELECT ON MONAN TO KHACHHANG
GRANT SELECT ON TAIKHOAN TO KHACHHANG
GRANT SELECT ON DOITAC TO KHACHHANG 
GRANT EXECUTE ON OBJECT::USP_KH_XEMDSMON TO KHACHHANG
GRANT EXECUTE ON OBJECT::USP_KH_TIMMONAN TO KHACHHANG
GRANT EXECUTE ON OBJECT::USP_KH_XEMDSDOITAC TO KHACHHANG
GRANT EXECUTE ON OBJECT::USP_KH_XEMDSCUAHANGCUADT TO KHACHHANG
GRANT EXECUTE ON OBJECT::USP_KH_XEMTHUCDON TO KHACHHANG
GRANT EXECUTE ON OBJECT::USP_KH_DATHANG TO KHACHHANG
GRANT EXECUTE ON OBJECT::USP_KH_DATHANG_CTDH TO KHACHHANG
GRANT EXECUTE ON OBJECT::USP_KH_XACNHANDON TO KHACHHANG
GRANT EXECUTE ON OBJECT::USP_KH_HUYDON TO KHACHHANG
GRANT EXECUTE ON OBJECT::USP_KH_THEODOIDH TO KHACHHANG
GRANT EXECUTE ON OBJECT::USP_KH_XEMCTDH TO KHACHHANG

EXEC sp_addlogin 'TK_DOITAC', 'TK_DOITAC12345', 'QL_HETHONGGIAONHANH';  
CREATE USER DOITAC FOR LOGIN TK_DOITAC

GRANT SELECT, INSERT ON HOPDONG TO DOITAC
GRANT SELECT ON DOITAC TO DOITAC
GRANT SELECT, UPDATE ON CUAHANG TO DOITAC
GRANT INSERT, SELECT, UPDATE, DELETE ON THUCDON TO DOITAC
GRANT INSERT, SELECT, UPDATE, DELETE ON MONAN TO DOITAC
GRANT SELECT ON DONHANG TO DOITAC
GRANT SELECT, UPDATE ON DONHANG(TINHTRANG) TO DOITAC
GRANT SELECT  ON PHANHOI TO DOITAC

GRANT EXECUTE ON OBJECT::USP_DKDOITAC TO DOITAC
GRANT EXECUTE ON OBJECT::USP_DT_DKHOPDONG TO DOITAC
GRANT EXECUTE ON OBJECT::USP_THEMCUAHANG TO DOITAC
GRANT EXECUTE ON OBJECT::USP_CAPNHATCUAHANG TO DOITAC
GRANT EXECUTE ON OBJECT::USP_THEMMONAN TO DOITAC
GRANT EXECUTE ON OBJECT::USP_XOAMONAN TO DOITAC
GRANT EXECUTE ON OBJECT::USP_CAPNHATMONAN TO DOITAC
GRANT EXECUTE ON OBJECT::USP_DOITACXEMDONHANG TO DOITAC
GRANT EXECUTE ON OBJECT::USP_DOITACAPNHATDONHANG TO DOITAC
GRANT EXECUTE ON OBJECT::USP_DOITAXEMDONHANGDANHAN TO DOITAC
GRANT EXECUTE ON OBJECT::USP_DOITAC_XEMDSDONHANG TO DOITAC
GRANT EXECUTE ON OBJECT::USP_DOITAC_XEMSLDONHANG TO DOITAC

EXEC sp_addlogin 'TK_NHANVIEN', 'TK_NHANVIEN12345', 'QL_HETHONGGIAONHANH';  
CREATE USER NHANVIEN FOR LOGIN TK_NHANVIEN
GRANT SELECT, UPDATE, INSERT ON NHANVIEN TO NHANVIEN
GRANT SELECT, UPDATE, INSERT ON HOPDONG TO NHANVIEN
GRANT SELECT ON DONHANG TO NHANVIEN
GRANT EXECUTE ON OBJECT::USP_NV_THONGKEKHACH_NGAY TO NHANVIEN
GRANT EXECUTE ON OBJECT::USP_NV_THONGKEDH TO NHANVIEN
GRANT EXECUTE ON OBJECT::USP_NV_THONGKEDOANHTHU TO NHANVIEN
GRANT EXECUTE ON OBJECT::USP_NV_DUYETHOPDONG TO NHANVIEN


EXEC sp_addlogin 'TK_TAIXE', 'TK_TAIXE12345', 'QL_HETHONGGIAONHANH';  
CREATE USER TAIXE FOR LOGIN TK_TAIXE

GRANT SELECT, UPDATE ON DONHANG TO TAIXE
GRANT SELECT ON TAIKHOAN TO TAIXE
GRANT SELECT, UPDATE ON TAIXE TO TAIXE

GRANT EXECUTE ON OBJECT::USP_TX_XEMDSDONHANG TO TAIXE
GRANT EXECUTE ON OBJECT::USP_TX_NHANDONHANG TO TAIXE
GRANT EXECUTE ON OBJECT::USP_TX_THEODOITHUNHAP TO TAIXE


