USE QL_HETHONGGIAONHANH

EXEC sp_addlogin 'TK_VODANH', 'TK_VODANH123', 'QL_HETHONGGIAONHANH';  
CREATE USER VODANH FOR LOGIN TK_VODANH

GRANT SELECT, INSERT ON TAIKHOAN TO VODANH
GRANT SELECT, INSERT ON KHACHHANG TO VODANH
GRANT EXECUTE ON OBJECT::USP_LOGIN TO VODANH
GRANT EXECUTE ON OBJECT::USP_CHECKUSERNAME TO VODANH
GRANT EXECUTE ON OBJECT::USP_CHECKPASS TO VODANH
GRANT EXECUTE ON OBJECT::USP_TAOTK_KHACHHANG TO VODANH

--drop login TK_VODANH
EXEC sp_addlogin 'TK_KHACHHANG', 'TK_KHACHHANG12345', 'QL_HETHONGGIAONHANH';  
CREATE USER KHACHHANG FOR LOGIN TK_KHACHHANG

GRANT SELECT, UPDATE ON KHACHHANG TO KHACHHANG
GRANT SELECT, INSERT ON DONHANG TO KHACHHANG
GRANT SELECT ON CUAHANG TO KHACHHANG
GRANT SELECT ON MONAN TO KHACHHANG
GRANT SELECT ON TAIKHOAN TO KHACHHANG
GRANT SELECT ON DOITAC TO KHACHHANG 
GRANT EXECUTE ON OBJECT::USP_KH_XEMDSMON TO KHACHHANG
GRANT EXECUTE ON OBJECT::USP_KH_TIMMONAN TO KHACHHANG
GRANT EXECUTE ON OBJECT::USP_KH_XEMDSDOITAC TO KHACHHANG
GRANT EXECUTE ON OBJECT::USP_KH_XEMDSCUAHANGCUADT TO KHACHHANG
GRANT EXECUTE ON OBJECT::USP_KH_XEMTHUCDON TO KHACHHANG
GRANT EXECUTE ON OBJECT::USP_KH_DATHANG TO KHACHHANG
GRANT EXECUTE ON OBJECT::USP_KH_DATHANG_CTDH TO KHACHHANG
GRANT EXECUTE ON OBJECT::USP_KH_XACNHANDON TO KHACHHANG
GRANT EXECUTE ON OBJECT::USP_KH_HUYDON TO KHACHHANG
GRANT EXECUTE ON OBJECT::USP_KH_THEODOIDH TO KHACHHANG
GRANT EXECUTE ON OBJECT::USP_KH_XEMCTDH TO KHACHHANG


--grant update, select
--on KHACHHANG
--to KHACHHANG

--grant select
--on DOITAC
--to KHACHHANG

--grant select
--on CUAHANG
--to KHACHHANG

--grant select
--on MONAN
--to KHACHHANG

--grant select
--on THUCDON 
--to KHACHHANG

--grant select
--on TUYCHONMON
--to KHACHHANG

--grant select
--on DONHANG
--to KHACHHANG

--grant update
--on DONHANG(TINHTRANG)
--to KHACHHANG

--grant select
--on CT_DONHANG
--to KHACHHANG
