--DOITAC
use QL_HETHONGGIAONHANH
--Đăng kí thông tin đối tác
DROP PROC IF EXISTS USP_DKDOITAC
GO
CREATE PROC USP_DKDOITAC
	@id VARCHAR(10),
	@username VARCHAR(20) ,
	@pass VARCHAR(20) ,
	@loaitk INT,

	@MADT varchar(10) ,
	@MASOTHUE varchar(10),
	@EMAIL varchar(50),
	@TENQUAN nvarchar(50),
	@NGUOIDAIDIEN nvarchar(50),
	@THANHPHO nvarchar(50),
	@QUAN nvarchar(50),
	@LOAIAMTHUC nvarchar(50),
	@DIACHIKINHDOANH nvarchar(50),
	@DIENTHOAI char(10),
	@SOLUONGCUAHANG char(10),
	@SOLUONGDHDUKIEN char(10)
AS
BEGIN 
	IF EXISTS (SELECT * FROM DOITAC WHERE MADT=@MADT OR MASOTHUE= @MASOTHUE)
	BEGIN
		PRINT N'dữ liệu đã tồn tại'
		RETURN 0
	END
	INSERT INTO TAIKHOAN
	VALUES
	(@id,@username,@pass,@loaitk)
	INSERT INTO DOITAC (MADT,TAIKHOAN, MASOTHUE, TENQUAN, NGUOIDAIDIEN,THANHPHO, QUAN, LOAIAMTHUC, DIACHIKINHDOANH, DIENTHOAI, SOLUONGCUAHANG, SOLUONGDHDUKIEN)
	VALUES(@MADT,@id, @MASOTHUE, @TENQUAN, @NGUOIDAIDIEN,@THANHPHO, @QUAN, @LOAIAMTHUC, @DIACHIKINHDOANH, @DIENTHOAI, @SOLUONGCUAHANG, @SOLUONGDHDUKIEN)
	RETURN 1
END 
GO
--SELECT * FROM DOITAC
----exec USP_DKDOITAC 'DT006','TK006','829','yzh44188@nezi8.com','American BluAs',N'Lê văn tanh',N'Hồ Na minh','',N'ăn vặt',N'100 tr?n hung d?o, hà n?i',093736656,5,8        
--đăng kí để lập hợp đồng
DROP PROC IF EXISTS USP_DT_DKHOPDONG
GO
CREATE PROC USP_DT_DKHOPDONG
	@MASOHOPDONG varchar(10),
	@NGAYLAP datetime,
	@THOIGIANHIEULUC datetime,
	@TAIKHOANNGANHANG varchar(20),
	--@PHIHOAHONG float,
	@MADT varchar(10)
	--@MASOTHUE varchar(10),
	--@MANV varchar(10),
	--@TINHTRANGDUYET int
AS
BEGIN 


	IF EXISTS (SELECT * FROM HOPDONG WHERE MASOHOPDONG=@MASOHOPDONG	AND @MADT=MADT)
	BEGIN
		PRINT N'Thông tin không phù hợp'
		RETURN -1
	END
	DECLARE @MASOTHUE varchar(10)
	SET @MASOTHUE = (SELECT MASOTHUE FROM DOITAC WHERE MADT = @MADT)
	INSERT INTO HOPDONG --(MASOHOPDONG, NGAYLAP, THOIGIANHIEULUC, TAIKHOANNGANHANG,PHIHOAHONG,MADT,MASOTHUE,MANV,TINHTRANGDUYET)
	VALUES(@MASOHOPDONG, @NGAYLAP, @THOIGIANHIEULUC, @TAIKHOANNGANHANG,100,@MADT,@MASOTHUE,NULL,0)
	RETURN 1
END
GO
--SELECT * FROM DOITAC
--SELECT * FROM HOPDONG
--exec USP_DT_DKHOPDONG 'HD006','20220918','20230222','050776527354',NULL,'DT006','106',NULL,0
--thêm cửa hàng
DROP PROC IF EXISTS USP_THEMCUAHANG
GO
CREATE PROC USP_THEMCUAHANG
	@MACUAHANG varchar(10),
	@MADT varchar(10),
	@TENCUAHANG nvarchar(50),
	@DIACHI nvarchar(50),
	@THOIGIANHOATDONG datetime,
	@TINHTRANGCUAHANG nvarchar(50)
AS
BEGIN 
	IF EXISTS (SELECT * FROM CUAHANG WHERE @MACUAHANG=MACUAHANG )
		BEGIN
			PRINT N'mã cửa hàng đã tồn tại'
			RETURN -1
		END
		INSERT INTO CUAHANG(MACUAHANG,MADT,TENCUAHANG,DIACHI,THOIGIANHOATDONG,TINHTRANGCUAHANG,ID_KHUVUC)
		VALUES (@MACUAHANG,@MADT,@TENCUAHANG,@DIACHI,@THOIGIANHOATDONG,@TINHTRANGCUAHANG,'kv1')
		RETURN 1
END
GO
--SELECT * FROM CUAHANG
----exec USP_THEMCUAHANG '008','DT001',N'mm',N'23 lê lợi, Quận 10','20220518 00:00:00','',kv1
--Cập nhật thông tin cửa hàng đã đăng kí
DROP PROC IF EXISTS USP_CAPNHATCUAHANG
GO
CREATE PROC USP_CAPNHATCUAHANG
	@MACUAHANG varchar(10),
	@MADT varchar(10),
	--@MASOTHUE varchar(10),
	@TENCUAHANG nvarchar(50),
	@DIACHI nvarchar(50),
	@THOIGIANHOATDONG datetime,
	@TINHTRANGCUAHANG nvarchar(50)
	--@ID_KHUVUC char(10)
AS
BEGIN 
	IF NOT EXISTS (SELECT * FROM CUAHANG WHERE @MACUAHANG=MACUAHANG AND @MADT=MADT )
		BEGIN
			PRINT N'dữ liệu không tồn tại'
			RETURN -1
		END
	UPDATE CUAHANG
	SET --MACUAHANG=@MACUAHANG,
		--MADT=@MADT,
		TENCUAHANG=@TENCUAHANG,
		DIACHI=@DIACHI,
		THOIGIANHOATDONG=@THOIGIANHOATDONG,
		TINHTRANGCUAHANG=@TINHTRANGCUAHANG
		--ID_KHUVUC = @ID_KHUVUC
	WHERE MACUAHANG=@MACUAHANG
	RETURN 1
END
GO

----exec USP_CAPNHATCUAHANG '001','DT001','Soul spectrum',N'18 lê lợi, Quận 9','20220518 00:00:00',''


--Thêm món ăn
DROP PROC IF EXISTS USP_THEMMONAN
GO
CREATE PROC USP_THEMMONAN
	@TENMON nvarchar(80),
	@MIEUTAMON nvarchar(50),
	@GIA float,
	@TINHTRANGMONAN nvarchar(50)
AS
BEGIN 
	IF EXISTS (SELECT * FROM MONAN WHERE TENMON=@TENMON)
		BEGIN
			PRINT N'dữ liệu đã tồn tại'
			RETURN -1
		END
	INSERT INTO MONAN (TENMON,MIEUTAMON,GIA,TINHTRANGMONAN)
	VALUES (@TENMON,@MIEUTAMON,@GIA,@TINHTRANGMONAN)
	RETURN 1
END 
GO
----exec USP_THEMMONAN N'Cánh gà','',30.000,N'Đã xử lý'
--SELECT * FROM MONAN
--Xóa món ăn
DROP PROC IF EXISTS USP_XOAMONAN
GO
CREATE PROC USP_XOAMONAN 
	@TENMON nvarchar(80),
	@MIEUTAMON nvarchar(50),
	@GIA float,
	@TINHTRANGMONAN nvarchar(50)
AS
BEGIN 
	IF NOT EXISTS (SELECT TENMON FROM MONAN WHERE TENMON=@TENMON)
		BEGIN 
			PRINT N'Tên món không tồn tại'
			RETURN -1
		END
	DELETE MONAN WHERE TENMON =@TENMON AND @MIEUTAMON=MIEUTAMON and GIA=@GIA and @TINHTRANGMONAN=TINHTRANGMONAN
	RETURN 1
END
GO 
----exec USP_XOAMONAN N'Cánh gà','',30.000,N'Đã xử lý'
--Cập nhật món ăn
DROP PROC IF EXISTS USP_CAPNHATMONAN
GO
CREATE PROC USP_CAPNHATMONAN
	@TENMON nvarchar(80),
	@MIEUTAMON nvarchar(50),
	@GIA float,
	@TINHTRANGMONAN nvarchar(50)
AS
BEGIN 
	IF NOT EXISTS (SELECT * FROM MONAN WHERE TENMON=@TENMON)
		BEGIN 
			PRINT N'Tên món không tồn tại'
			RETURN -1
		END

	UPDATE MONAN
	SET MIEUTAMON = @MIEUTAMON,
		GIA =@GIA,
		TINHTRANGMONAN= @TINHTRANGMONAN
	WHERE TENMON = @TENMON 
	return 1
END 
GO

--Xem đơn hàng
DROP PROC IF EXISTS USP_DOITACXEMDONHANG
GO
CREATE PROC USP_DOITACXEMDONHANG
	@MADT varchar(10)
AS
BEGIN TRAN
	SELECT DH.* FROM DONHANG DH JOIN CT_DONHANG CT_DH ON CT_DH.MADON = DH.MADON AND CT_DH.MADT = @madt
COMMIT TRAN
GO
--exec USP_DOITACXEMDONHANG 'DT001'
--Cập nhật tình trạng đơn hàng
DROP PROC IF EXISTS USP_DOITACAPNHATDONHANG
GO
CREATE PROC USP_DOITACAPNHATDONHANG
	@MADON varchar(5),
	@MADT varchar(10)
	--@TINHTRANG nvarchar(50)
AS
BEGIN 
	IF NOT EXISTS (SELECT DH.* FROM DONHANG DH JOIN CT_DONHANG CT_DH ON CT_DH.MADON = DH.MADON AND CT_DH.MADT = @madt)
	BEGIN
		PRINT @MADON + N' Không tồn tại'
		RETURN -1
	END
	IF NOT EXISTS (SELECT DH.* FROM DONHANG DH JOIN CT_DONHANG CT_DH ON DH.TINHTRANG= N'Đã xác nhận')
	BEGIN
		PRINT N' Không tồn tại đơn hàng nào để xác nhận là đang chuẩn bị'
		RETURN -2
	END
	--IF EXISTS (SELECT DH.* FROM DONHANG DH JOIN CT_DONHANG CT_DH ON DH.TINHTRANG= N'Đã xác nhận')
	--BEGIN
	--	PRINT N' Đơn hàng đã được xác nhận'
	--	RETURN -3
	--END
	UPDATE DONHANG 
	SET TINHTRANG = N'Đang chuẩn bị'
	WHERE MADON = @MADON AND TINHTRANG = N'Đã xác nhận'
	RETURN 1
END
GO
SELECT * FROM DONHANG
SELECT * FROM CT_DONHANG
--exec USP_DOITACAPNHATDONHANG 'DH001','DT001' 

--Xem danh sách đơn hàng đã nhận
DROP PROC IF EXISTS USP_DOITAXEMDONHANGDANHAN
GO
CREATE PROC USP_DOITAXEMDONHANGDANHAN
	@MADT varchar(10)
AS
BEGIN
	SELECT DH.* FROM DONHANG DH JOIN CT_DONHANG CT_DH ON CT_DH.MADON = DH.MADON AND CT_DH.MADT = @madt
	WHERE TINHTRANG =N'Chờ xác nhận'
END
----exec USP_DOITAXEMDONHANGDANHAN 'DT001'
--Xem đơn hàng theo ngày, tháng, năm
GO
DROP PROC IF EXISTS USP_DOITAC_XEMDSDONHANG
GO
CREATE PROC USP_DOITAC_XEMDSDONHANG
	@NGAYLAP DATETIME,
	@MADT varchar (10)
AS
BEGIN 
	SELECT DH.* FROM DONHANG DH JOIN CT_DONHANG CT_DH ON CT_DH.MADON = DH.MADON AND CT_DH.MADT = @madt WHERE DH.NGAYLAP= @NGAYLAP 
END
SELECT * FROM DONHANG
SELECT * FROM CT_DONHANG
exec USP_DOITAC_XEMDSDONHANG '2021-12-09','DT001'
--

-- Xem số lượng đơn theo ngày, tháng năm
GO
DROP PROC IF EXISTS USP_DOITAC_XEMSLDONHANG
GO
CREATE PROC USP_DOITAC_XEMSLDONHANG
	@NGAYLAP DATETIME,
	@MADT varchar (10)
AS
BEGIN 
	SELECT COUNT  (distinct DH.MADON) FROM DONHANG DH JOIN CT_DONHANG CT_DH ON CT_DH.MADON = DH.MADON AND CT_DH.MADT =@MADT WHERE DH.NGAYLAP=@NGAYLAP 
END
SELECT * FROM DONHANG
SELECT * FROM CT_DONHANG
exec USP_DOITAC_XEMSLDONHANG '20210618','DT001'

--xem số lượng đơn hàng theo tháng 
--GO
--DROP PROC IF EXISTS USP_DT_XEMDHTHEOTHANG
--GO
--CREATE PROC USP_DT_XEMDHTHEOTHANG 
--	@madt varchar(10), 
--	@thang int
--AS
--BEGIN
--	SELECT DH.* FROM DONHANG DH JOIN CT_DONHANG CT_DH ON CT_DH.MADON = DH.MADON AND CT_DH.MADT = @madt WHERE MONTH(NGAYGIAO) = @thang AND dh.TINHTRANG = N'Chờ xác nhận' 
--END
--SELECT * FROM DONHANG
--SELECT * FROM CT_DONHANG
--exec USP_DT_XEMDHTHEOTHANG 'DT001','12'
--theo dõi doanh thu theo ngày
GO
DROP PROC IF EXISTS USP_DOITAC_DOANHTHU_NGAY
GO
CREATE PROC USP_DOITAC_DOANHTHU_NGAY
	@NGAYLAP DATETIME,
	@MADT varchar (10)
AS
BEGIN 
	
	IF NOT EXISTS (SELECT * FROM DONHANG WHERE @NGAYLAP=NGAYLAP)
	BEGIN	
		PRINT N'hông tìm thấy đơn hàng có ngày lập này!!'
		--ROLLBACK TRAN
		RETURN -1
	END
	DECLARE @TONGDOANHTHU FLOAT
	SET @TONGDOANHTHU = (SELECT SUM (DH.TONGTIEN) FROM DONHANG DH JOIN CT_DONHANG CT ON CT.MADT= @MADT WHERE TINHTRANG = N'Đã giao' AND CT.MADON=DH.MADON AND NGAYLAP=@NGAYLAP  )
	SELECT @TONGDOANHTHU
	RETURN 1
END
SELECT * FROM DONHANG 
SELECT * FROM CT_DONHANG
----exec USP_DOITAC_DOANHTHU_NGAY '2021-06-18 00:00:00.000','DT001'
--XEM DANH SÁCH ĐƠN HÀNG ĐÃ HỦY
--DROP PROC IF EXISTS USP_DOITAXEMDONHANGDAHUY
--GO
--CREATE PROC USP_DOITAXEMDONHANGDAHUY
--AS
--BEGIN
--	SELECT * FROM DONHANG 
--	WHERE TINHTRANG =N'Đã hủy'
--END


--XEM PHẢN HỒI CỦA KHÁCH HÀNG
GO
DROP PROC IF EXISTS USP_XEMPHANHOI
GO
CREATE PROC USP_XEMPHANHOI
AS
BEGIN
	SELECT * FROM PHANHOI 
END

--SELECT * FROM HOPDONG
----exec USP_DKHOPDONG 'HD006','20220918 00:00:00','20230222 00:00:00','050776527354',150.000,'DT006','811','241782293',1




--KHACH HANG
-- 1 được 0 lỗi
--kiểm tra tên đăng nhập
GO
DROP PROC IF EXISTS USP_CHECKUSERNAME
GO
CREATE PROC USP_CHECKUSERNAME
	@username VARCHAR(20)
AS
BEGIN
	IF EXISTS (SELECT * FROM TAIKHOAN WHERE USERNAME = @username)
	RETURN 1
	ELSE RETURN 0
END
GO

-- DROP PROC SP_KTMatKhau
-- Kiểm tra mật khẩu
GO
DROP PROC IF EXISTS USP_CHECKPASS
GO
CREATE PROC USP_CHECKPASS
	@username VARCHAR(20),
	@pass  VARCHAR(20)
AS
BEGIN	
	-- kiểm tra	
	IF EXISTS (SELECT * FROM TAIKHOAN WHERE  USERNAME = @username AND PASS = @pass)
	RETURN 1
	ELSE RETURN 0
END


--VÔ DANH
--đăng nhập
GO
DROP PROC IF EXISTS USP_LOGIN
GO
CREATE PROC USP_LOGIN
	@USERNAME VARCHAR(20),
	@PASS VARCHAR(20),
	@ID CHAR(5) OUTPUT,
	@LOAITK INT OUTPUT
AS
BEGIN	
	SET @ID = 'NULL'

	-- lấy mã tài khoản		
	SET @ID = (SELECT ID
				FROM TAIKHOAN
				WHERE USERNAME = @USERNAME
				AND PASS = @PASS)

	-- lấy loại tài khoản		
	SET @LOAITK = (SELECT LOAITK
				FROM TAIKHOAN
				WHERE USERNAME = @USERNAME
				AND PASS = @PASS)
	--print @id + @loaitk
	-- xử lí đăng nhập
	if (@ID != 'NULL')
	BEGIN
		PRINT N'Đăng nhập thành công'
		RETURN 1
	END
	ELSE RETURN 0	
END
GO

--SELECT *
--				FROM TAIKHOAN

--				declare @tong varchar(10)
--				declare @t int
----exec USP_LOGIN 'kh1','123456789',@tong,@t
 

--thêm tài khoản khách hàng
GO
DROP PROC IF EXISTS USP_TAOTK_KHACHHANG
GO
CREATE PROC USP_TAOTK_KHACHHANG
	@id VARCHAR(10),
	@username VARCHAR(20) ,
	@pass VARCHAR(20) ,
	@loaitk INT,
	@makhach VARCHAR(10),
	@tenkhach nvarchar(30),
	@sdt CHAR(10) ,
	@email VARCHAR(30),
	@diachi nvarchar(300)
AS
BEGIN	
	--Kiểm tra mã KH
	IF EXISTS (SELECT MAKHACH FROM KHACHHANG WHERE MAKHACH = @makhach)
	BEGIN
		PRINT N'MÃ KH ĐÃ TỒN TẠI'
		RETURN 0
	END

	--Kiểm tra ID
	IF EXISTS (SELECT ID FROM TAIKHOAN WHERE ID = @ID)
	BEGIN
		PRINT N'ID ĐÃ TỒN TẠI'
		RETURN -1
	END
	
	-- xử lí thêm bảng TAIKHOAN
	INSERT INTO TAIKHOAN
	VALUES
	(@id,@username,@pass,@loaitk)

	-- xử lí thêm bảng KHACHHANG
	INSERT INTO KHACHHANG
	VALUES
	(@makhach,@id,@tenkhach,@sdt,@diachi,@email)

	RETURN 1

END

--PHÂN HỆ KHÁCH HÀNG

--Khách hàng xem danh sách món ăn
GO
DROP PROC IF EXISTS USP_KH_XEMDSMON
GO
CREATE PROC USP_KH_XEMDSMON
AS
BEGIN
	SELECT * FROM MONAN
END
GO


--Khách hàng tìm món ăn theo tên
GO
DROP PROC IF EXISTS USP_KH_TIMMONAN 
GO
CREATE PROC USP_KH_TIMMONAN
	@tenmon nvarchar(80)
AS
BEGIN
	IF NOT EXISTS (SELECT * FROM MONAN WHERE TENMON = @tenmon)
	BEGIN
		PRINT @tenmon + N' Không tồn tại'
		RETURN
	END
	SELECT TD.MADT, TD.MACUAHANG, TD.TENMON, MA.GIA, SOLUONGTON, MIEUTAMON, TINHTRANGMONAN
	FROM THUCDON TD
	JOIN MONAN MA ON TD.TENMON = MA.TENMON
	WHERE TD.TENMON LIKE N'%'+ @tenmon + '%'
	--WHERE TENMON LIKE @tenmon
END

----exec USP_KH_TIMMONAN N'cHÁO gà'


--Khách hàng xem danh sách đối tác
GO
DROP PROC IF EXISTS USP_KH_XEMDSDOITAC 
GO
CREATE PROC USP_KH_XEMDSDOITAC
AS
BEGIN
	SELECT MADT, TENQUAN, THANHPHO, QUAN, LOAIAMTHUC, DIENTHOAI, EMAIL, SOLUONGCUAHANG FROM DOITAC
END


--Khách hàng xem danh sách cửa hàng của đối tác.
GO
DROP PROC IF EXISTS USP_KH_XEMDSCUAHANGCUADT 
GO
CREATE PROC USP_KH_XEMDSCUAHANGCUADT
	@madt varchar(10)
AS
BEGIN
	IF NOT EXISTS (SELECT * FROM DOITAC WHERE MADT = @madt)
	BEGIN
		PRINT @madt + N' Không tồn tại'
		RETURN
	END

	 SELECT MADT, MACUAHANG, TENCUAHANG, DIACHI, THOIGIANHOATDONG, TINHTRANGCUAHANG FROM CUAHANG  WHERE MADT = @madt
END

GO
DROP PROC IF EXISTS USP_KH_XEMTHUCDON
GO
CREATE PROC USP_KH_XEMTHUCDON
	@madt varchar(10),
	@mach varchar(10)
AS
BEGIN
	 SELECT MONAN.TENMON, GIA, SOLUONGTON, MIEUTAMON , TINHTRANGMONAN FROM THUCDON JOIN MONAN ON MONAN.TENMON = THUCDON.TENMON  
	 WHERE MADT = @madt AND MACUAHANG = @mach 
END


--Khách hàng đặt hàng

GO
DROP PROC IF EXISTS USP_KH_DATHANG
GO
CREATE PROC USP_KH_DATHANG
	@madt varchar(10),
	@mach varchar(10),
	@madon varchar(10),
	@ngaymua datetime,
	--@ngaygiao datetime,
	@makh varchar(10),
	@hinhthuctt nvarchar(50),
	@diachigiaohang nvarchar(300),
	@phisp float,
	@phivc float,
	@tongtien float

AS
BEGIN 
	IF EXISTS (SELECT * FROM DONHANG WHERE MADON = @madon)
	BEGIN
		PRINT N'MÃ ĐƠN HÀNG ĐÃ TỒN TẠI'
		RETURN 0
	END

	--Kiểm tra mã KH	
	IF (@MAKH != NULL)
		IF (@MAKH != NULL AND NOT EXISTS (SELECT MAKHACH FROM KHACHHANG WHERE MAKHACH = @MAKH))
		BEGIN
			PRINT N'MÃ KHÁCH KHÔNG TỒN TẠI'
			RETURN -1
		END
	DECLARE @IDKV VARCHAR(10)
	SET @IDKV = (SELECT ID_KHUVUC FROM CUAHANG WHERE MACUAHANG=@mach AND MADT=@madt)
	INSERT INTO DONHANG VALUES(@madon,@ngaymua,@hinhthuctt,@diachigiaohang,@phisp,@phivc,@tongtien,N'Chờ xác nhận',NULL,@makh,NULL,@IDKV)
	RETURN 1
END
GO

--Thêm sản phẩm vào chi tiết hóa đơn
GO
DROP PROC IF EXISTS USP_KH_DATHANG_CTDH
GO
CREATE PROC USP_KH_DATHANG_CTDH
	@tenmon nvarchar(80),
	@madon varchar(10),
	@soluong int,
	@madt varchar(10),
	@mach varchar(10),
	@thanhtien float
AS
BEGIN 

	IF NOT EXISTS (SELECT TENMON FROM MONAN WHERE TENMON LIKE N'%'+ @tenmon + '%')
	BEGIN
		PRINT N'MÓN ĂN KHÔNG TỒN TẠI'
		RETURN 0
	END

	IF NOT EXISTS (SELECT MADON FROM DONHANG WHERE MADON = @madon)
	BEGIN
		PRINT N'MÃ ĐƠN HÀNG KHÔNG TỒN TẠI'
		RETURN -1
	END

	
	INSERT INTO CT_DONHANG
	VALUES (@madon,@mach, @madt,@tenmon,@soluong,@thanhtien)

	RETURN 1
END
GO


--Khách hàng xác nhận đơn
----CHỖ NÀY KO CHẤC********************************
DROP PROC IF EXISTS USP_KH_XACNHANDON
GO
CREATE PROC USP_KH_XACNHANDON
	@madon varchar(10)
AS
BEGIN
	IF NOT EXISTS (SELECT * FROM DONHANG WHERE MADON = @madon)
	BEGIN
		PRINT @madon + N' Không tồn tại'
		RETURN -1
	END

	UPDATE DONHANG
	SET TINHTRANG =  N'Đã xác nhận'
	WHERE MADON = @madon
	RETURN 1
END

--GO

--khách hàng hủy đơn
GO
DROP PROC IF EXISTS USP_KH_HUYDON
GO
CREATE PROC USP_KH_HUYDON
	@madon varchar(5)
AS
BEGIN
	IF NOT EXISTS (SELECT * FROM DONHANG WHERE MADON = @madon)
	BEGIN
		PRINT @madon + N' Không tồn tại'
		RETURN -1
	END
	
	DELETE 
	FROM CT_DONHANG
	WHERE MADON = @madon

	UPDATE DONHANG
	SET TINHTRANG = N'Đã hủy'


	RETURN 1
END


--khách hàng theo dõi đơn hàng
GO
DROP PROC IF EXISTS USP_KH_THEODOIDH 
GO
CREATE PROC USP_KH_THEODOIDH
	@makhach varchar(10)
AS
BEGIN
	IF NOT EXISTS (SELECT * FROM DONHANG WHERE MAKHACH = @makhach)
	BEGIN
		PRINT @makhach + N' Không Có Đơn Hàng'
		RETURN
	END

	SELECT MADON, NGAYLAP, HINHTHUCTT, DIACHIGIAO, PHISP, PHIVC, TONGTIEN, TINHTRANG, NGAYGIAO, TAIXE FROM DONHANG
	WHERE  MAKHACH = @makhach
END
GO

--khách hàng xem chi tiết đơn hàng
GO
DROP PROC IF EXISTS USP_KH_XEMCTDH
GO
CREATE PROC USP_KH_XEMCTDH
	@madon VARCHAR(15)	
AS
BEGIN	
	--Kiểm tra mã DH
	IF NOT EXISTS (SELECT MADON FROM DONHANG WHERE MADON = @madon)
	BEGIN
		PRINT N'MÃ ĐƠN KHÔNG TỒN TẠI'
		RETURN 0
	END

	-- lấy thông tin 
	SELECT CTDH.MADON, CTDH.MADT, CTDH.MACUAHANG,CTDH.TENMON, MA.GIA, CTDH.SOLUONG, CTDH.THANHTIEN 
	FROM CT_DONHANG CTDH JOIN MONAN MA ON CTDH.TENMON = MA.TENMON
	WHERE CTDH.MADON = @madon
	
	RETURN 1
END
GO


--khách hàng đánh giá món ăn
--select * from PHANHOI
GO
DROP PROC IF EXISTS USP_KH_DANHGIAMON
GO
CREATE PROC USP_KH_DANHGIAMON
	@tenmon nvarchar(80),
	@makhach varchar(10),
	@danhgia char(7),
	@binhluan nvarchar(100)
AS
BEGIN
	IF NOT EXISTS (SELECT TENMON FROM MONAN WHERE TENMON = @tenmon)
	BEGIN
		PRINT @tenmon + N' Không tồn tại'
		RETURN -1
	END
	IF NOT EXISTS (SELECT MAKHACH FROM KHACHHANG WHERE MAKHACH = @makhach)
	BEGIN
		PRINT @makhach + N' Không tồn tại'
		RETURN 0
	END
	INSERT INTO PHANHOI
	VALUES (@tenmon,@makhach,@danhgia,@binhluan)
	RETURN 1
END

--EXEC USP_KH_DANHGIAMON N'Cháo gà','KH001','LIKE',N'ddam'


GO
USE QL_HETHONGGIAONHANH
GO

--PHÂN HỆ NHÂN VIÊN
--Nhân viên xem danh sách hợp đồng của đối tác
GO
DROP PROC IF EXISTS USP_NV_XEMDSHOPDONG
GO
CREATE PROC USP_NV_XEMDSHOPDONG @madt varchar(10)
AS
BEGIN
	SELECT * FROM DOITAC dt JOIN HOPDONG hd ON hd.MADT = dt.MADT
	WHERE dt.MADT = @madt
END

--Nhân viên xem thống kê lượng khách hàng của từng đối tác theo ngày
GO
DROP PROC IF EXISTS USP_NV_THONGKEKHACH_NGAY
GO
CREATE PROC USP_NV_THONGKEKHACH_NGAY @ngay datetime
AS
BEGIN
	SELECT kh.* FROM KHACHHANG KH JOIN DONHANG DH ON dh.NGAYGIAO = @ngay AND dh.TINHTRANG = N'Đã giao' AND dh.MAKHACH = kh.MAKHACH
END
--exec USP_NV_THONGKEKHACH_NGAY '20210519'


--Nhân viên xem thống kê lượng khách hàng của từng đối tác theo tháng
GO
DROP PROC IF EXISTS USP_NV_THONGKEKHACH_THANG
GO
CREATE PROC USP_NV_THONGKEKHACH_THANG @madt varchar(10), @thang int, @nam int
AS
BEGIN
	SELECT kh.* FROM  KHACHHANG KH JOIN DONHANG DH ON MONTH(dh.NGAYGIAO) = @thang AND YEAR(dh.NGAYGIAO) = @nam AND dh.TINHTRANG = N'Chờ xác nhận' AND dh.MAKHACH = kh.MAKHACH
	
END
SELECT * FROM DONHANG
--exec USP_NV_THONGKEKHACH_NGAY '20210619'

--Nhân viên xem danh sách hợp đồng sắp hết hạn
GO
DROP PROC IF EXISTS USP_NV_XEMDSHOPDONG_HETHAN
GO
CREATE PROC USP_NV_XEMDSHOPDONG_HETHAN @mahd varchar(10), @hieuluc datetime
AS
BEGIN
	SELECT * FROM HOPDONG hd WHERE DATEDIFF(DAY, hd.THOIGIANHIEULUC, hd.NGAYLAP) < 30
END

--Nhân viên thống kê lượng đơn hàng, doanh thu của từng đối tác
GO
DROP PROC IF EXISTS USP_NV_THONGKEDH
GO
CREATE PROC USP_NV_THONGKEDH @madt varchar(10)
AS
BEGIN
		IF(NOT EXISTS (SELECT * FROM DOITAC WHERE MADT = @madt))
	BEGIN
		PRINT N'Không tồn tại đối tác nào có mã như trên'
		return
	END

	SELECT DH.* FROM DONHANG DH JOIN CT_DONHANG CT_DH ON CT_DH.MADON = DH.MADON AND CT_DH.MADT = @madt

END
--exec USP_NV_THONGKEDH 'DT002'
SELECT * FROM CT_DONHANG 
-- chỖ NÀY T HONG BIẾT SAO ĐỂ TRUY XUẤT ĐẾN ĐUUNGS ĐỐI TÁC                            
GO
DROP PROC IF EXISTS USP_NV_THONGKEDOANHTHU
GO
CREATE PROC USP_NV_THONGKEDOANHTHU @madt varchar(10)
AS
BEGIN
	IF(NOT EXISTS (SELECT * FROM DOITAC WHERE MADT = @madt))
	BEGIN
		PRINT N'Không tồn tại đối tác nào có mã như trên'
		return
	END

	SELECT SUM(DH.PHISP) + SUM(DH.PHIVC) AS DOANHTHU FROM DONHANG DH JOIN CT_DONHANG CT_DH ON DH.MADON=CT_DH.MADON
	WHERE TINHTRANG=N'Đã giao' AND CT_DH.MADT=@madt
END
--exec SP_NV_THONGKEDOANHTHU 'DT004'
--Nhân viên thống kê số lượng đơn hàng, hoa hồng từ các đơn hàng của từng đối tác
--GO
--DROP PROC IF EXISTS USP_NV_THONGKEHOAHONG
--GO
--CREATE PROC USP_NV_THONGKEHOAHONG @madt varchar(10), @mahd varchar(10), @thang int, @nam int
--AS
--BEGIN
--	IF(NOT EXISTS (SELECT * FROM DOITAC WHERE MADT = @madt))
--	BEGIN
--		PRINT N'Không tồn tại đối tác nào có mã như trên'
--		return
--	END

--	DECLARE @total INT, @tonghoahong FLOAT
--	SET @total = (SELECT COUNT(dh.MADON) FROM DONHANG dh)
--	SET @tonghoahong = (SELECT SUM(hd.PHIHOAHONG) FROM HOPDONG hd WHERE MADT = @madt AND YEAR(hd.NGAYLAP) AND MONTH(hd.NGAYLAP))
--	RETURN @tonghoahong
--END


--Nhân viên xem danh sách hợp đồng đã lập của đối tác
GO
DROP PROC IF EXISTS USP_NV_XEMDSHOPDONG_DUYET
GO
CREATE PROC USP_NV_XEMDSHOPDONG_DUYET @madt varchar(10)
AS
BEGIN
	SELECT * FROM DOITAC dt JOIN HOPDONG hd ON hd.MADT = dt.MADT
	WHERE dt.MADT = @madt AND hd.TINHTRANGDUYET = N'Đã duyệt'
END

--Nhân viên duyệt hợp đồng
GO
DROP PROC IF EXISTS USP_NV_DUYETHOPDONG
GO
CREATE PROC USP_NV_DUYETHOPDONG @mahd varchar(10),
								@ngaylap datetime,
								@thoigianhieuluc datetime,
								@taikhoanNH varchar(20),
								@phihoahong float,
								@madt varchar(10),
								@masothue varchar(10),
								@manv varchar(10),
								@tinhtrangduyet int
AS
BEGIN
	IF NOT EXISTS (SELECT * FROM HOPDONG WHERE @mahd = MASOHOPDONG AND @madt = MADT)
	BEGIN
		PRINT N'dữ liệu không tồn tại'
	END
	UPDATE HOPDONG 
	SET TINHTRANGDUYET = @tinhtrangduyet
	WHERE MASOHOPDONG = @mahd
END

--1. Tài xế đăng ký thông tin (Tạo tài khoản)
GO
DROP PROC IF EXISTS UPS_TX_TAOTK
GO
CREATE PROC UPS_TX_TAOTK
	@CMND varchar(12),
	@TAIKHOAN char(5),
	@HOTEN nvarchar(30),
	@DIENTHOAI char(10),
	@DIACHI nvarchar(30),
	@EMAIL varchar(20),
	@BIENSOXE varchar(5),
	@TAIKHOANNGANHANG char(15),
	@PHITHUECHAN float,
	@ID_KHUVUC char(10),
	@USERNAME VARCHAR(20),
	@pass VARCHAR(20),
	@LOAITK int
AS
BEGIN
	--Kiểm tra Mã TX đã tồn tại chưa
	IF EXISTS (SELECT CMND FROM TAIXE WHERE CMND = @CMND)
	BEGIN
		PRINT(N'MÃ TÀI XẾ ĐÃ TỒN TẠI')
		RETURN
	END

	--KIỂM TRA TÀI KHOẢN
	IF EXISTS (SELECT ID FROM TAIKHOAN WHERE ID = @TAIKHOAN)
	BEGIN
		PRINT(N'ID ĐÃ TỒN TẠI')
		RETURN
	END

	--XỬ LÍ THÊM VÀO BẢNG TAIKHOAN
	INSERT INTO TAIKHOAN VALUES (@TAIKHOAN, @USERNAME, @pass, @LOAITK)

	--XỬ LÍ THÊM VÀO BẢNG TAIXE
	INSERT INTO TAIXE VALUES (@CMND, @TAIKHOAN, @HOTEN, @DIENTHOAI, @DIACHI, @EMAIL, @BIENSOXE, @TAIKHOANNGANHANG, @PHITHUECHAN, @ID_KHUVUC)

END
GO
use QL_HETHONGGIAONHANH
----------
GO
DROP PROC IF EXISTS UPS_TX_TAOTK
GO
CREATE PROC UPS_TX_TAOTK
	@CMND varchar(12),
	@HOTEN nvarchar(30),
	@DIENTHOAI char(10),
	@DIACHI nvarchar(30),
	@EMAIL varchar(20),
	@BIENSOXE varchar(5),
	@TAIKHOANNGANHANG char(15),
	@PHITHUECHAN float,
	@ID_KHUVUC char(10),
	@ID char(5),
	@USERNAME VARCHAR(20),
	@pass VARCHAR(20),
	@LOAITK int
AS
BEGIN
	--Kiểm tra Mã TX đã tồn tại chưa
	IF EXISTS (SELECT CMND FROM TAIXE WHERE CMND = @CMND)
	BEGIN
		PRINT(N'MÃ TÀI XẾ ĐÃ TỒN TẠI')
		ROLLBACK
		RETURN 0
	END

	--KIỂM TRA TÀI KHOẢN
	IF EXISTS (SELECT ID FROM TAIKHOAN WHERE ID = @ID)
	BEGIN
		PRINT(N'ID ĐÃ TỒN TẠI')
		ROLLBACK
		RETURN -1
	END

	--XỬ LÍ THÊM VÀO BẢNG TAIKHOAN
	INSERT INTO TAIKHOAN VALUES (@ID, @USERNAME, @pass, @LOAITK)

	--XỬ LÍ THÊM VÀO BẢNG TAIXE
	INSERT INTO TAIXE VALUES (@CMND, @ID, @HOTEN, @DIENTHOAI, @DIACHI, @EMAIL, @BIENSOXE, @TAIKHOANNGANHANG, @PHITHUECHAN, @ID_KHUVUC)
	
	RETURN 1
END
GO

--2. Tài xế xem danh sách đơn hàng trong khu vực 
GO
DROP PROC IF EXISTS USP_TX_XEMDSDONHANG
GO
CREATE PROC USP_TX_XEMDSDONHANG
	@taikhoan varchar(12)
AS
BEGIN
	DECLARE @ID_KHUVUC_TX char(10)
	SELECT @ID_KHUVUC_TX = (SELECT ID_KHUVUC FROM TAIXE WHERE TAIXE.TAIKHOAN = @taikhoan)

	SELECT * FROM DONHANG WHERE DONHANG.ID_KHUVUC = @ID_KHUVUC_TX AND DONHANG.TINHTRANG != N'Đã giao' AND DONHANG.TINHTRANG != N'ĐANG GIAO'
END
GO




--exec USP_TX_XEMDSDONHANG 'TK007'

--3. Tài xế chọn đơn hàng, cập nhật tình trạng đơn hàng
GO
DROP PROC IF EXISTS USP_TX_NHANDONHANG
GO
CREATE PROC USP_TX_NHANDONHANG
	@MADON varchar(10),
	@CMND_TX varchar(12)
AS
BEGIN
	IF NOT EXISTS (SELECT * FROM DONHANG WHERE MADON = @MADON)
	BEGIN
		PRINT @MADON + N' không tồn tại'
		RETURN
	END

	IF((SELECT TINHTRANG FROM DONHANG DH, TAIXE TX WHERE MADON = @MADON AND DH.ID_KHUVUC = TX.ID_KHUVUC) != N'Đang chuẩn bị')
	BEGIN
		PRINT @MADON + N' chưa được xác nhận hoặc đã được nhận bởi tài xế khác'
		RETURN
	END


	UPDATE DONHANG SET TINHTRANG = N'Đang giao' WHERE MADON = @MADON AND TAIXE = @CMND_TX
	PRINT N'Tài xế nhận đơn ' + @MADON + N' thành công'
END



--4. Tài xế theo dõi thu nhập
GO
DROP PROC IF EXISTS USP_TX_THEODOITHUNHAP
GO
CREATE PROC USP_TX_THEODOITHUNHAP
	@taikhoan char(5)
AS
BEGIN
	
	----KIỂM TRA MÃ TÀI XẾ CÓ TỒN TẠI KHÔNG
	--IF NOT EXISTS (SELECT CMND FROM TAIXE WHERE CMND = @CMND_TX)
	--BEGIN
	--	PRINT (N'MÃ TÀI XẾ KHÔNG TỒN TẠI')
	--	RETURN
	--END

	DECLARE @CMND_TX varchar(12)
	SELECT @CMND_TX = (SELECT CMND FROM TAIXE WHERE TAIXE.TAIKHOAN = @taikhoan)

	--KIỂM TRA TÀI XẾ ĐÃ GIAO ĐƠN NÀO THÀNH CÔNG CHƯA
	IF((SELECT COUNT(PHIVC) FROM DONHANG WHERE TAIXE = @CMND_TX AND TINHTRANG = N'ĐÃ GIAO') = 0)
	BEGIN
		PRINT(N'TÀI XẾ CHƯA CÓ THU NHẬP')
		RETURN
	END

	SELECT MADON, PHIVC , NGAYGIAO FROM DONHANG WHERE TAIXE = @CMND_TX and TINHTRANG = N'ĐÃ GIAO'
	
END
--select * from TAIKHOAN
--select taikhoan from TAIXE
--exec USP_TX_THEODOITHUNHAP 'TK006'