USE QL_HETHONGGIAONHANH

-- 1 được 0 lỗi
--kiểm tra tên đăng nhập
GO
DROP PROC IF EXISTS USP_CHECKUSERNAME
GO
CREATE PROC USP_CHECKUSERNAME
	@username VARCHAR(20)
AS
BEGIN
	IF EXISTS (SELECT * FROM TAIKHOAN WHERE USERNAME = @username)
	RETURN 1
	ELSE RETURN 0
END
GO

-- DROP PROC SP_KTMatKhau
-- Kiểm tra mật khẩu
GO
DROP PROC IF EXISTS USP_CHECKPASS
GO
CREATE PROC USP_CHECKPASS
	@username VARCHAR(20),
	@pass  VARCHAR(20)
AS
BEGIN	
	-- kiểm tra	
	IF EXISTS (SELECT * FROM TAIKHOAN WHERE  USERNAME = @username AND PASS = @pass)
	RETURN 1
	ELSE RETURN 0
END


--VÔ DANH
--đăng nhập
GO
DROP PROC IF EXISTS USP_LOGIN
GO
CREATE PROC USP_LOGIN
	@USERNAME VARCHAR(20),
	@PASS VARCHAR(20),
	@ID CHAR(5) OUTPUT,
	@LOAITK INT OUTPUT
AS
BEGIN	
	SET @ID = 'NULL'

	-- lấy mã tài khoản		
	SET @ID = (SELECT ID
				FROM TAIKHOAN
				WHERE USERNAME = @USERNAME
				AND PASS = @PASS)

	-- lấy loại tài khoản		
	SET @LOAITK = (SELECT LOAITK
				FROM TAIKHOAN
				WHERE USERNAME = @USERNAME
				AND PASS = @PASS)
	--print @id + @loaitk
	-- xử lí đăng nhập
	if (@ID != 'NULL')
	BEGIN
		PRINT N'Đăng nhập thành công'
		RETURN 1
	END
	ELSE RETURN 0	
END
GO

--SELECT *
--				FROM TAIKHOAN

--				declare @tong varchar(10)
--				declare @t int
--EXEC USP_LOGIN 'kh1','123456789',@tong,@t
 

--thêm tài khoản khách hàng
GO
DROP PROC IF EXISTS USP_TAOTK_KHACHHANG
GO
CREATE PROC USP_TAOTK_KHACHHANG
	@id VARCHAR(10),
	@username VARCHAR(20) ,
	@pass VARCHAR(20) ,
	@loaitk INT,
	@makhach VARCHAR(10),
	@tenkhach nvarchar(30),
	@sdt CHAR(10) ,
	@email VARCHAR(30),
	@diachi nvarchar(300)
AS
BEGIN	
	--Kiểm tra mã KH
	IF EXISTS (SELECT MAKHACH FROM KHACHHANG WHERE MAKHACH = @makhach)
	BEGIN
		PRINT N'MÃ KH ĐÃ TỒN TẠI'
		RETURN 0
	END

	--Kiểm tra ID
	IF EXISTS (SELECT ID FROM TAIKHOAN WHERE ID = @ID)
	BEGIN
		PRINT N'ID ĐÃ TỒN TẠI'
		RETURN -1
	END
	
	-- xử lí thêm bảng TAIKHOAN
	INSERT INTO TAIKHOAN
	VALUES
	(@id,@username,@pass,@loaitk)

	-- xử lí thêm bảng KHACHHANG
	INSERT INTO KHACHHANG
	VALUES
	(@makhach,@id,@tenkhach,@sdt,@diachi,@email)

	RETURN 1

END

--PHÂN HỆ KHÁCH HÀNG

--Khách hàng xem danh sách món ăn
GO
DROP PROC IF EXISTS USP_KH_XEMDSMON
GO
CREATE PROC USP_KH_XEMDSMON
AS
BEGIN
	SELECT * FROM MONAN
END
GO


--Khách hàng tìm món ăn theo tên
GO
DROP PROC IF EXISTS USP_KH_TIMMONAN 
GO
CREATE PROC USP_KH_TIMMONAN
	@tenmon nvarchar(80)
AS
BEGIN
	IF NOT EXISTS (SELECT * FROM MONAN WHERE TENMON = @tenmon)
	BEGIN
		PRINT @tenmon + N' Không tồn tại'
		RETURN
	END
	SELECT TD.MADT, TD.MACUAHANG, TD.TENMON, MA.GIA, SOLUONGTON, MIEUTAMON, TINHTRANGMONAN
	FROM THUCDON TD
	JOIN MONAN MA ON TD.TENMON = MA.TENMON
	WHERE TD.TENMON LIKE N'%'+ @tenmon + '%'
	--WHERE TENMON LIKE @tenmon
END

--exec USP_KH_TIMMONAN N'cHÁO gà'


--Khách hàng xem danh sách đối tác
GO
DROP PROC IF EXISTS USP_KH_XEMDSDOITAC 
GO
CREATE PROC USP_KH_XEMDSDOITAC
AS
BEGIN
	SELECT MADT, TENQUAN, THANHPHO, QUAN, LOAIAMTHUC, DIENTHOAI, EMAIL, SOLUONGCUAHANG FROM DOITAC
END


--Khách hàng xem danh sách cửa hàng của đối tác.
GO
DROP PROC IF EXISTS USP_KH_XEMDSCUAHANGCUADT 
GO
CREATE PROC USP_KH_XEMDSCUAHANGCUADT
	@madt varchar(10)
AS
BEGIN
	IF NOT EXISTS (SELECT * FROM DOITAC WHERE MADT = @madt)
	BEGIN
		PRINT @madt + N' Không tồn tại'
		RETURN
	END

	 SELECT MADT, MACUAHANG, TENCUAHANG, DIACHI, THOIGIANHOATDONG, TINHTRANGCUAHANG FROM CUAHANG  WHERE MADT = @madt
END

GO
DROP PROC IF EXISTS USP_KH_XEMTHUCDON
GO
CREATE PROC USP_KH_XEMTHUCDON
	@madt varchar(10),
	@mach varchar(10)
AS
BEGIN
	 SELECT MONAN.TENMON, GIA, SOLUONGTON, MIEUTAMON , TINHTRANGMONAN FROM THUCDON JOIN MONAN ON MONAN.TENMON = THUCDON.TENMON  
	 WHERE MADT = @madt AND MACUAHANG = @mach 
END


--TẠO MÃ ĐƠN
--GO
--DROP PROC IF EXISTS TAOMADON
--GO
--CREATE PROC TAOMADON
--	@madon VARCHAR(10) OUT
--AS
--BEGIN
--	DECLARE @sldh int
--	SET @sldh = (SELECT COUNT(*) FROM DONHANG)
--	SET @sldh =  @sldh + 1
--	DECLARE @count varchar(10)

--	SET @count = '00' + CONVERT(varchar,@sldh)
--	SET @madon = 'DH' + RIGHT(@count, 8)

--END
--Khách hàng đặt hàng

GO
DROP PROC IF EXISTS USP_KH_DATHANG
GO
CREATE PROC USP_KH_DATHANG
	@madt varchar(10),
	@mach varchar(10),
	@madon varchar(10),
	@ngaymua datetime,
	@ngaygiao datetime,
	@makh varchar(10),
	@hinhthuctt nvarchar(50),
	@diachigiaohang nvarchar(300),
	@phisp float,
	@phivc float,
	@tongtien float

AS
BEGIN 
	IF EXISTS (SELECT * FROM DONHANG WHERE MADON = @madon)
	BEGIN
		PRINT N'MÃ ĐƠN HÀNG ĐÃ TỒN TẠI'
		RETURN 0
	END

	--Kiểm tra mã KH	
	IF (@MAKH != NULL)
		IF (@MAKH != NULL AND NOT EXISTS (SELECT MAKHACH FROM KHACHHANG WHERE MAKHACH = @MAKH))
		BEGIN
			PRINT N'MÃ KHÁCH KHÔNG TỒN TẠI'
			RETURN -1
		END
	DECLARE @IDKV VARCHAR(10)
	SET @IDKV = (SELECT ID_KHUVUC FROM CUAHANG WHERE MACUAHANG=@mach and MADT = @madt)
	INSERT INTO DONHANG VALUES(@madon,@ngaymua,@hinhthuctt,@diachigiaohang,@phisp,@phivc,@tongtien,N'Chờ xác nhận',@ngaygiao,@makh,NULL,@IDKV)
	RETURN 1
END
GO

--EXEC USP_KH_DATHANG 'DT003','003','DH007','2022-2-3','2022-12-12','KH003','COD','O22',39,34,NULL
--Thêm sản phẩm vào chi tiết hóa đơn
GO
DROP PROC IF EXISTS USP_KH_DATHANG_CTDH
GO
CREATE PROC USP_KH_DATHANG_CTDH
	@tenmon nvarchar(80),
	@madon varchar(10),
	@soluong int,
	@madt varchar(10),
	@mach varchar(10),
	@thanhtien float
AS
BEGIN 
--SELECT * FROM CT_DONHANG
	IF NOT EXISTS (SELECT TENMON FROM MONAN WHERE TENMON LIKE N'%'+ @tenmon + '%')
	BEGIN
		PRINT N'MÓN ĂN KHÔNG TỒN TẠI'
		RETURN 0
	END

	IF NOT EXISTS (SELECT MADON FROM DONHANG WHERE MADON = @madon)
	BEGIN
		PRINT N'MÃ ĐƠN HÀNG KHÔNG TỒN TẠI'
		RETURN -1
	END

	
	INSERT INTO CT_DONHANG
	VALUES (@madon,@mach, @madt,@tenmon,@soluong,@thanhtien)

	RETURN 1
END
GO
select * from CT_DONHANG
EXEC USP_KH_DATHANG_CTDH N'Cơm chiên','DH006',3,'DT003','003',null

--Khách hàng xác nhận đơn
----CHỖ NÀY KO CHẤC********************************
DROP PROC IF EXISTS USP_KH_XACNHANDON
GO
CREATE PROC USP_KH_XACNHANDON
	@madon varchar(10)
AS
BEGIN
	IF NOT EXISTS (SELECT * FROM DONHANG WHERE MADON = @madon)
	BEGIN
		PRINT @madon + N' Không tồn tại'
		RETURN -1
	END

	UPDATE DONHANG
	SET TINHTRANG =  N'Đã xác nhận'
	WHERE MADON = @madon
	RETURN 1
END

--GO

--khách hàng hủy đơn
GO
DROP PROC IF EXISTS USP_KH_HUYDON
GO
CREATE PROC USP_KH_HUYDON
	@madon varchar(5)
AS
BEGIN
	IF NOT EXISTS (SELECT * FROM DONHANG WHERE MADON = @madon)
	BEGIN
		PRINT @madon + N' Không tồn tại'
		RETURN -1
	END
	
	DELETE 
	FROM CT_DONHANG
	WHERE MADON = @madon

	--DELETE  
	--FROM DONHANG
	--WHERE MADON = @madon
	UPDATE DONHANG
	SET TINHTRANG = N'Đã hủy'
	WHERE MADON = @madon

	RETURN 1
END


--khách hàng theo dõi đơn hàng
GO
DROP PROC IF EXISTS USP_KH_THEODOIDH 
GO
CREATE PROC USP_KH_THEODOIDH
	@makhach varchar(10)
AS
BEGIN
	IF NOT EXISTS (SELECT * FROM DONHANG WHERE MAKHACH = @makhach)
	BEGIN
		PRINT @makhach + N' Không Có Đơn Hàng'
		RETURN
	END

	SELECT MADON, NGAYLAP, HINHTHUCTT, DIACHIGIAO, PHISP, PHIVC, TONGTIEN, TINHTRANG, NGAYGIAO, TAIXE FROM DONHANG
	WHERE  MAKHACH = @makhach
END
GO

--khách hàng xem chi tiết đơn hàng
GO
DROP PROC IF EXISTS USP_KH_XEMCTDH
GO
CREATE PROC USP_KH_XEMCTDH
	@madon VARCHAR(15)	
AS
BEGIN	
	--Kiểm tra mã DH
	IF NOT EXISTS (SELECT MADON FROM DONHANG WHERE MADON = @madon)
	BEGIN
		PRINT N'MÃ ĐƠN KHÔNG TỒN TẠI'
		RETURN 0
	END

	-- lấy thông tin 
	SELECT CTDH.MADON, CTDH.MADT, CTDH.MACUAHANG,CTDH.TENMON, MA.GIA, CTDH.SOLUONG, CTDH.THANHTIEN 
	FROM CT_DONHANG CTDH JOIN MONAN MA ON CTDH.TENMON = MA.TENMON
	WHERE CTDH.MADON = @madon
	
	RETURN 1
END
GO
